---
title: "CONW trend models"
format: html
editor: visual
---

## Collection of trend models applied to CONW

Connecticut Warbler population trends are partly dependent on the model and the underlying geographic stratifications.

To explore the among-model variation in our understanding of the species' population trends, we fit the data to two models, each at two different spatial-grained stratifications. The two models are a GAMYE and a first-difference model (). The two stratifications are a coarse-grained stratification based on the intersection of BCRs (Bird Conservation Regions) that we refer to here as the `"bbs_usgs"` and a finer-grained stratification based on a latitude by longitude 1-degree grid-cell that we refer to here as `"latlong"`.

## Model fitting

We used the R package `bbsBayes2`.

```{r, message=FALSE}
library(bbsBayes2)
library(tidyverse)

models <- c("gamye","first_diff")
stratifications <- c("latlong","bbs_usgs")
species <- "Connecticut Warbler"

for(m in models){
  for(stratification in stratifications){
    min_n <- ifelse(stratification == "latlong",1,3)
    s <- stratify(by = stratification,
                  species = species)
    p <- prepare_data(s,
                      min_n_routes = min_n,
                      min_max_route_years = 5)
    ps <- prepare_spatial(p,strata_map = load_map(stratification))
    
    pm <- prepare_model(ps,
                  model = m,
                  model_variant = "spatial")
    
    saveRDS(pm,paste0("data/",model,"_",stratification,".rds"))
    
    m <- run_model(pm)
    
    
  }
}



```

We prepare the data setting the minimum number of routes to different values depending on the stratification used. For the coarse-grain stratification, we use the 3-route minimum cut-off to reflect the thresholds used by the CWS and USGS in their agency-led annual analyses. For the fine-grain stratification, we use a minimum of 1-route, to include the largest number of strata and to reflect the underlying design of the BBS. For all estimates, we also set a higher minimum for the number of non-zero observations on a given route to ensure that each included route and stratum has more reliable data for estimating change in abundance over time.
