---
title: "Methods"
format: docx
editor: visual
bibliography: references.bib
---

## Methods

## Trends

To explore the among-model variation in our understanding of the species' population trends, we fit the data to two models, each at two different stratifications to estimate trends at different spatial-grains. The two models are a GAMYE and a first-difference model (). The two stratifications are: 1) a coarse-grained stratification based on the intersection of political jurisdictions (states, provinces, territories) and Bird Conservation Regions, (BCRs); and 2) a fine-grained stratification based on a latitude by longitude 1-degree grid-cell.

We fit the data with two models to assess some of the model-dependent variation in the estimated population trajectories and the trends derived from the trajectories. The GAMYE model estimates trajectories that are combinations of a non-linear smooth and annual fluctuations [@smith2020][@smith2023]. The first-difference model estimates trajectories that follow a random-walk through time, where the estimated annual abundance in each year is a function of the annual abundance in the previous year [@link2017][@smith2023]. For both models, we used spatially explicit versions to more accurately estimate trends and to highlight the spatial patterns in trends across the species' range [@smith2023]. These two models represent time-series structures used by the two national agencies that estimate population trends from the BBS: the GAMYE is used by the Canadian Wildlife Service, the first-difference is used by the United States Geological Survey.

We used the two stratifications to assess the dependency of the estimated local trajectories and trends on the spatial grain, and the dependency of the composite regional and survey-wide estimates on the area-weights for each stratum. The broad- and fine-grained stratifications vary in the area of each stratum, which results in differences in the number of BBS routes and differences in the area-weights associated with any given BBS routes. The broad-grained stratification groups larger numbers of BBS routes into a fewer overall number of strata, so that estimates of trends within a given stratum are generally estimated with higher precision because of the greater number of observations. The use of the broad-strata also applies area-weights to the strata-level estimates of trajectories and trends that assume the relative abundances and trends apply across the full stratum (Political jurisdiction by BCR). In practice, this results in a much greater weight given to the trend information for the relatively few BBS routes in the northern strata (where large strata have relatively few BBS routes) when calculating the composite national and survey-wide estimates, in comparison to the routes in the southern part of the species' range (where smaller strata generally have more BBS routes). The fine-grained stratification includes relatively fewer BBS routes in each stratum and therefore estimates in a given stratum are generally of lower precision. However, it also allows for much finer resolution of trend information in space that can help understand the variation in trends across the species' range. The composite national and survey-wide estimates apply much more consistent area-weights to information from any given BBS route across the species' range. The smaller and more consistently sized strata reduce the variation among strata in the number of BBS routes and the area-weights for each stratum. Therefore in practice, this finer stratification weights the information from different parts of the species' range in a way that reflects the portions of the species' range for which there are BBS data. However, it may therefore be biased by the sampling imbalance of the BBS survey, because the distribution of BBS routes is strongly biased towards the south where there is a much higher density of roads and observers to conduct the surveys. The fine grained stratification also represents the original design stratification of the BBS. BBS routes are established using a start-location and direction of travel randomly selected along a secondary road within a given grid cell.

## Monitoring coverage

To complement the trend analyses, we also assessed the monitoring coverage, i.e., the proportion of the species current population that is overlapped by the BBS monitoring information. We used data on the spatial distribution of relative abundance during the breeding season derived from eBird data [@johnston2020][@strimas-mackey2022]. This relative abundance surface provides an internally consistent spatial layer of the species' abundance, estimated for the year 2021 [@strimas-mackey2022]. We overlayed this relative abundance surface with a grid representing the regions with long-term BBS monitoring information for Connecticut Warblers. This grid was defined by the grid-cells of the original design stratification of the BBS program that include at least one BBS route, on which Connecticut Warblers have been observed in more than one year at any point since 1996: the 1-degree longitude by latitude finer resolution spatial stratification. Any grid-cell that contributed information to a trend model (Figure X) was considered "covered" in this analysis. We calculated the proportion of the relative abundance surface within the grid-cells that have BBS monitoring data (i.e., grid cells with at least one BBS route where the species has been observed). We calculated this proportion by first summing the high-resolution raster values (3km x 3km) of the estimated breeding season relative abundance downloaded through the eBirdst R package [@strimas-mackey2022] within each grid-cell.

To account for the differences between the long-term information from the BBS, the more recent information from the eBird abundance surface, we extrapolated the relative abundance information to ensure that all of the grid-cells that had long-term monitoring data also had a non-zero value for relative abundance. For grid cells that included long-term BBS monitoring data, but were outside of the current modeled species relative abundance surface, we filled those grid cells with the relative abundance values from the nearest grid-cell that did overlap the modeled abundance. We adjusted the filled values of relative abundance to account for differences in the area of land between the filled cell and the nearest neighbour, so that the filled values represented an area-corrected sum of relative abundance. Most of these differences reflect regions that have historical Connecticut Warbler observations but where the population has decreased substantially and may no longer have sufficient abundance to warrant inclusion in the breeding range map, relative to the rest of the species' current range. We acknowledge that this way of correcting the current relative abundance surface to be more comparable to the historical monitoring data from the BBS is adhoc, but we suggest that a fulsome analysis of the coverage of the program is beyond the scope of this work, due to the potential complexities in understanding changes in local abundance, shifting ranges, variations in field methods, seasonal survey timing, and modeling.
